// <auto-generated />
using System;
using FRIO.MAR.INFRA.REPOSITORY.SQLSERVER.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FRIO.MAR.INFRA.REPOSITORY.SQLSERVER.Migrations
{
    [DbContext(typeof(SIFMContext))]
    [Migration("20220310061045_TablaAdjuntosFactura2")]
    partial class TablaAdjuntosFactura2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.AccesoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SitioWeb")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("AccesoUsuario");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", b =>
                {
                    b.Property<long>("BodegaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("BodegaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Bodega");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFactura", b =>
                {
                    b.Property<long>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaId");

                    b.ToTable("CFactura");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaAdjunto", b =>
                {
                    b.Property<long>("FacturaAdjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagenBase64")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ruta")
                        .HasColumnType("varchar(max)");

                    b.HasKey("FacturaAdjuntoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("CFacturaAdjunto");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaDetalle", b =>
                {
                    b.Property<long>("FacturaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BodegaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("CodigoSeguimiento")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IvaValor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("FacturaId");

                    b.ToTable("CFacturaDetalle");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaFormaPago", b =>
                {
                    b.Property<long>("FacturaFormaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoFormaPago")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DescripcionFormaPago")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("FormaPagoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaFormaPagoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("CFacturaFormaPago");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("varchar(3)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CodigoSeguimiento", b =>
                {
                    b.Property<long>("CodigoSeguimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductoClienteId")
                        .HasColumnType("bigint");

                    b.HasKey("CodigoSeguimientoId");

                    b.ToTable("CodigoSeguimiento");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Correo", b =>
                {
                    b.Property<long>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Adjunto")
                        .HasColumnType("int");

                    b.Property<string>("Asunto")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Copias")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Correos")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<int?>("IntentosEnvio")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .HasColumnType("varchar(5000)")
                        .HasMaxLength(5000)
                        .IsUnicode(false);

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdCorreo")
                        .HasName("PK__Correo__872F8EAEDC7FA84E");

                    b.ToTable("Correo");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Factura", b =>
                {
                    b.Property<long>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaAdjunto", b =>
                {
                    b.Property<long>("FacturaAdjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagenBase64")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ruta")
                        .HasColumnType("varchar(max)");

                    b.HasKey("FacturaAdjuntoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaAdjunto");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaDetalle", b =>
                {
                    b.Property<long>("FacturaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BodegaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("CodigoSeguimiento")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(300)");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IvaValor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaDetalle");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaFormaPago", b =>
                {
                    b.Property<long>("FacturaFormaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoFormaPago")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DescripcionFormaPago")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("FormaPagoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("FacturaFormaPagoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaFormaPago");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Facturador", b =>
                {
                    b.Property<long>("FacturadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Logo")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PuntoEmision")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sucursal")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("varchar(5)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("FacturadorId");

                    b.ToTable("Facturador");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Impuesto", b =>
                {
                    b.Property<int>("ImpuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("TipoImpuestoId")
                        .HasColumnType("int");

                    b.HasKey("ImpuestoId");

                    b.HasIndex("TipoImpuestoId");

                    b.ToTable("Impuesto");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioConfiguracionesGenerales", b =>
                {
                    b.Property<long>("IdInventarioConfiguracionesGenerales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("ControlInventarioEmision")
                        .HasColumnType("bit");

                    b.Property<bool?>("ControlInventarioSucursal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DescontarStockAutomatico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<long>("IdCompania")
                        .HasColumnType("bigint");

                    b.HasKey("IdInventarioConfiguracionesGenerales")
                        .HasName("PK__Invent__2D482365639E2D77");

                    b.ToTable("InventarioConfiguracionesGenerales");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioMovimientoEntrada", b =>
                {
                    b.Property<long>("IdInventarioMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("CodigoTransferencia")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Cufe")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdInventarioBodega")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdProveedor")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSucursal")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnName("IP")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(5000)")
                        .HasMaxLength(5000)
                        .IsUnicode(false);

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("TipoInventario")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdInventarioMovimiento")
                        .HasName("PK__Invent__4D66004A55C73884");

                    b.HasIndex("IdInventarioBodega");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("InventarioMovimientoEntrada");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioMovimientoSalida", b =>
                {
                    b.Property<long>("IdInventarioMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("CodigoTransferencia")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Cufe")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdInventarioBodega")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSucursal")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnName("IP")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(5000)")
                        .HasMaxLength(5000)
                        .IsUnicode(false);

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("TipoInventario")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdInventarioMovimiento")
                        .HasName("PK__Invent__4D66004AE5E880D4");

                    b.HasIndex("IdInventarioBodega");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("InventarioMovimientoSalida");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioProveedor", b =>
                {
                    b.Property<long>("IdInventarioProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CantidadDescripcion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdInventarioBodega")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSucursal")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnName("IP")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<decimal?>("StockActual")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdInventarioProveedor")
                        .HasName("PK__Invent__17576659E0B70AEB");

                    b.HasIndex("IdInventarioBodega");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("InventarioProveedor");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioVenta", b =>
                {
                    b.Property<long>("IdInventarioVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CantidadDescripcion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdInventarioBodega")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdProducto")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSucursal")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnName("IP")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<decimal?>("StockActual")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdInventarioVenta")
                        .HasName("PK__Invent__3FAD48D7775D9CA1");

                    b.HasIndex("IdInventarioBodega");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("InventarioVenta");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Notificacion", b =>
                {
                    b.Property<long>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EsNotificacionLeida")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaNotificacionLeida")
                        .HasColumnType("datetime");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("TipoCriticidad")
                        .HasColumnType("int");

                    b.Property<int>("TipoNotificacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("IdNotificacion")
                        .HasName("PK_EVNotificacion");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Parametros", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("Codigo");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Permisos", b =>
                {
                    b.Property<long>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Icono")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<long?>("IdPadre")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("NombreAbreviado")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Url")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdPermiso")
                        .HasName("PK__SPPermis__0D626EC845308855");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("IvaCodigo")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("IvaPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoCliente", b =>
                {
                    b.Property<long>("ProductoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("ProductoClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ProductoCliente");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoClienteImagen", b =>
                {
                    b.Property<long>("ProductoClienteImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenBase64")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ProductoClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ruta")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ProductoClienteImagenId");

                    b.HasIndex("ProductoClienteId");

                    b.ToTable("ProductoClienteImagen");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoImagen", b =>
                {
                    b.Property<long>("ProductoImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenBase64")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ruta")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ProductoImagenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoImagen");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Proveedor", b =>
                {
                    b.Property<long>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("varchar(3)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Rol", b =>
                {
                    b.Property<long>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584CB35FDE7B");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.RolPermiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("IdPermiso")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdRol")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", b =>
                {
                    b.Property<long>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("SucursalId");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.SucursalBodega", b =>
                {
                    b.Property<long>("SucursalBodegaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BodegaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(15)");

                    b.Property<long>("SucursalId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("SucursalBodegaId");

                    b.HasIndex("BodegaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("SucursalBodega");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.TipoIdentificacion", b =>
                {
                    b.Property<long>("TipoIdentificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TipoIdentificacionId");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.TipoImpuesto", b =>
                {
                    b.Property<int>("TipoImpuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(4)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TipoImpuestoId");

                    b.ToTable("TipoImpuesto");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("UnidadMedidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Simbolo")
                        .HasColumnType("varchar(max)");

                    b.HasKey("UnidadMedidaId");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizarPassword")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimaConexion")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long?>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioEliminacion")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("IdUsuario")
                        .HasName("PK__SPUsuari__5B65BF97D476A28D");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<long?>("IdRol")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUsuario")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", null)
                        .WithMany("Bodega")
                        .HasForeignKey("SucursalId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaAdjunto", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.CFactura", "Factura")
                        .WithMany("FacturaAdjunto")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaDetalle", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.CFactura", "Factura")
                        .WithMany("FacturaDetalle")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.CFacturaFormaPago", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.CFactura", "Factura")
                        .WithMany("FacturaFormaPago")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaAdjunto", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Factura", "Factura")
                        .WithMany("FacturaAdjunto")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Factura", "Factura")
                        .WithMany("FacturaDetalle")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.FacturaFormaPago", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Factura", "Factura")
                        .WithMany("FacturaFormaPago")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.Impuesto", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.TipoImpuesto", "TipoImpuesto")
                        .WithMany("Impuestos")
                        .HasForeignKey("TipoImpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioMovimientoEntrada", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", "Bodega")
                        .WithMany("InventarioMovimientoEntrada")
                        .HasForeignKey("IdInventarioBodega")
                        .HasConstraintName("FK__Inventa__IdInv__0AFD888E");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Producto", "IdProductoNavigation")
                        .WithMany("InventarioMovimientoEntrada")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventa__IdPro__0A096455");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", "IdSucursalNavigation")
                        .WithMany("InventarioMovimientoEntrada")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Inventa__IdSuc__0BF1ACC7");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioMovimientoSalida", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", "Bodega")
                        .WithMany("InventarioMovimientoSalida")
                        .HasForeignKey("IdInventarioBodega")
                        .HasConstraintName("FK__Inventa__IdInv__0638D371");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Producto", "IdProductoNavigation")
                        .WithMany("InventarioMovimientoSalida")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventa__IdPro__0544AF38");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", "IdSucursalNavigation")
                        .WithMany("InventarioMovimientoSalida")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Inventa__IdSuc__072CF7AA");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioProveedor", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", "Bodega")
                        .WithMany("InventarioProveedor")
                        .HasForeignKey("IdInventarioBodega")
                        .HasConstraintName("FK__Inventa__IdInv__1392CE8F");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Producto", "IdProductoNavigation")
                        .WithMany("InventarioProveedor")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventa__IdPro__129EAA56");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", "IdSucursalNavigation")
                        .WithMany("InventarioProveedor")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Inventa__IdSuc__22D5121F");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.InventarioVenta", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", "Bodega")
                        .WithMany("InventarioVenta")
                        .HasForeignKey("IdInventarioBodega")
                        .HasConstraintName("FK__Inventa__IdInv__0FC23DAB");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Producto", "IdProductoNavigation")
                        .WithMany("InventarioVenta")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventa__IdPro__0ECE1972");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", "IdSucursalNavigation")
                        .WithMany("InventarioVenta")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Inventa__IdSuc__21E0EDE6");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoCliente", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Cliente", "Cliente")
                        .WithMany("ProductoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoClienteImagen", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.ProductoCliente", "ProductoCliente")
                        .WithMany("ProductoClienteImagen")
                        .HasForeignKey("ProductoClienteId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.ProductoImagen", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Producto", "Producto")
                        .WithMany("ProductoImagen")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.RolPermiso", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Permisos", "IdPermisoNavigation")
                        .WithMany("RolPermiso")
                        .HasForeignKey("IdPermiso")
                        .HasConstraintName("FK__RolPerm__IdPer__3F466844");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Rol", "IdRolNavigation")
                        .WithMany("RolPermiso")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__RolPerm__IdRol__3E52440B");
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.SucursalBodega", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Bodega", "Bodega")
                        .WithMany("SucursalBodega")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Sucursal", "Sucursal")
                        .WithMany("SucursalBodega")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FRIO.MAR.APPLICATION.CORE.Entities.UsuarioRol", b =>
                {
                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Rol", "IdRolNavigation")
                        .WithMany("UsuarioRol")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuario__IdRol__3C69FB99");

                    b.HasOne("FRIO.MAR.APPLICATION.CORE.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioRol")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Usuario__IdUsu__3B75D760");
                });
#pragma warning restore 612, 618
        }
    }
}
